package com.talend.framework.metadata_framework.tdc;

import com.talend.framework.metadata_framework.model.ColumnDef;
import com.talend.framework.metadata_framework.model.Dataset;
import com.talend.framework.metadata_framework.model.JobLineageGraph;
import com.talend.framework.metadata_framework.model.LineageEdge;
import org.springframework.stereotype.Component;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Pattern;

/**
 * Serializes a {@link JobLineageGraph} into a Talend Data Catalog
 * "Data Mapping Script" — SQL-DML-like text that the Data Mapping Script
 * import bridge parses into data stores and data-flow lineage.
 *
 * <p>Output shape (one {@code SELECT ... INTO ... FROM ...} per edge):
 * <pre>
 *   CREATE CONNECTION "PostgreSQL" TYPE "Relational Database";
 *   SELECT customer_id AS customer_id
 *   INTO   bronze.customers@"PostgreSQL"
 *   FROM   landing/customers.csv@"FileSystem";
 * </pre>
 *
 * <p><b>Column mapping is best-effort.</b> The audit table records the schema
 * of each side but not a column-to-column mapping, so each statement projects
 * the <i>target</i> columns as {@code name AS name}. This yields column-level
 * nodes and table-level lineage; it assumes name-preserving mappings. When a
 * dataset has no known columns the statement falls back to {@code SELECT *}
 * (table-level lineage only).
 */
@Component
public class DataMappingScriptWriter {

    private static final Pattern SIMPLE_IDENTIFIER = Pattern.compile("[A-Za-z_][A-Za-z0-9_]*");

    public String write(JobLineageGraph graph) {
        Map<String, Dataset> byId = new LinkedHashMap<>();
        for (Dataset d : graph.datasets()) {
            byId.put(d.id(), d);
        }

        StringBuilder sb = new StringBuilder();
        writeHeader(sb, graph);
        writeConnections(sb, graph.datasets());

        for (LineageEdge edge : graph.edges()) {
            Dataset source = byId.get(edge.sourceDatasetId());
            Dataset target = byId.get(edge.targetDatasetId());
            if (source == null || target == null) {
                continue;
            }
            writeStatement(sb, edge, source, target);
        }
        return sb.toString();
    }

    private void writeHeader(StringBuilder sb, JobLineageGraph graph) {
        sb.append("-- Talend Data Catalog — Data Mapping Script\n");
        sb.append("-- Generated by metadata-framework from the ETL audit table.\n");
        sb.append("-- Job: ").append(graph.jobName()).append('\n');
        if (graph.latestEventTimestamp() != null) {
            sb.append("-- Latest audit event: ").append(graph.latestEventTimestamp()).append('\n');
        }
        sb.append("-- Connection names below are stitched to harvested data stores in TDC.\n\n");
    }

    private void writeConnections(StringBuilder sb, List<Dataset> datasets) {
        // One CREATE CONNECTION per distinct connection name. A connection that
        // serves files is "File System"; one that serves tables is "Relational
        // Database". First dataset seen for a name wins (the builder never mixes).
        Map<String, String> typeByConnection = new LinkedHashMap<>();
        for (Dataset d : datasets) {
            if (d.connectionName() == null) {
                continue;
            }
            String type = d.kind() == Dataset.Kind.FILE ? "File System" : "Relational Database";
            typeByConnection.putIfAbsent(d.connectionName(), type);
        }
        for (Map.Entry<String, String> e : typeByConnection.entrySet()) {
            sb.append("CREATE CONNECTION \"").append(e.getKey())
                    .append("\" TYPE \"").append(e.getValue()).append("\";\n");
        }
        if (!typeByConnection.isEmpty()) {
            sb.append('\n');
        }
    }

    private void writeStatement(StringBuilder sb, LineageEdge edge, Dataset source, Dataset target) {
        if (edge.stage() != null) {
            sb.append("-- ").append(edge.stage().name());
            if (edge.component() != null) {
                sb.append(" via ").append(edge.component());
            }
            sb.append('\n');
        }

        sb.append("SELECT ").append(projection(target)).append('\n');
        sb.append("INTO   ").append(reference(target)).append('\n');
        sb.append("FROM   ").append(reference(source)).append(";\n\n");
    }

    /** Target columns as {@code name AS name}, or {@code *} when none are known. */
    private String projection(Dataset target) {
        List<ColumnDef> columns = target.columns();
        if (columns == null || columns.isEmpty()) {
            return "*";
        }
        StringBuilder cols = new StringBuilder();
        for (int i = 0; i < columns.size(); i++) {
            String name = identifier(columns.get(i).name());
            if (i > 0) {
                cols.append(",\n       ");
            }
            cols.append(name).append(" AS ").append(name);
        }
        return cols.toString();
    }

    /** {@code schema.table@"Conn"} for tables, {@code path@"Conn"} for files. */
    private String reference(Dataset d) {
        String object = d.kind() == Dataset.Kind.TABLE && d.schemaName() != null
                ? d.schemaName() + "." + d.name()
                : d.name();
        return object + "@\"" + d.connectionName() + "\"";
    }

    private String identifier(String raw) {
        if (raw == null || raw.isBlank()) {
            return "\"\"";
        }
        return SIMPLE_IDENTIFIER.matcher(raw).matches()
                ? raw
                : "\"" + raw.replace("\"", "\"\"") + "\"";
    }
}
